title:        Avasz's Journals
tagline:      "Avasz's Journals"
description:  'Another <em>mostly</em> Open Source related blog.'
url:          http://avashmulmi.com.np
author:
  name:       'Avasz'
  email:      'avashmulmi.com.np'
markdown:    kramdown 
permalink:    pretty
pygments:     true
paginate:     5
